name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - uses: actions/checkout@v3

      - name: Debug
        run: echo BUCKET ${{ secrets.BUCKET }} BUCKET

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn Install
        run: yarn install

      - name: Webpack
        run: yarn webpack

      - name: Deploy
        run:  yarn deploy:s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          KEY: ${{ secrets.KEY }}
